# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Usa una versión reciente y estable
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=700'] # Aumentar límite para uv.lock
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11 # Coincide con tu versión de Ruff
    hooks:
    -   id: ruff-check # Ejecuta el linter de Ruff con autofix
        name: "Ruff Linter"
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format # Ejecuta el formateador de Ruff
        name: "Ruff Formatter"
